# Site settings
title: Vivero Fellows 2018 Bootcamp
email: waldenka@grinnell.edu
description: > # this means to ignore newlines until "baseurl:"
  Tutorials and resources for 2018 Vivero Fellows bootcamp.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: kwaldenphd
github_username:  kwalden2018

# Build settings
markdown: kramdown
highlighter: rouge
pygments: false
encoding: utf-8
